# Generated by Django 4.1.5 on 2024-03-12 19:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_product_images'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopChart',
            new_name='ShopCart',
        ),
    ]
