# Generated by Django 4.1.5 on 2024-03-13 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 17, 37, 48, 614973)),
        ),
        migrations.AddField(
            model_name='coupon',
            name='notes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='coupon',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 17, 37, 48, 614973)),
        ),
    ]
