# Generated by Django 4.1.5 on 2024-03-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_coupon_create_at_coupon_notes_coupon_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
