# Generated by Django 4.1.5 on 2024-03-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_usercoupon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='used',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10),
        ),
    ]
